
// =============================================
// This Class is generated by BuildProject
// Author:	Bop
// Create date:	07/09/2016 20:08
// Description:	
// Revise History:	
// =============================================

using System;
using System.Data;
using System.Data.SqlClient;
using System.Data.Sql;
using System.Linq;
using System.Data.Common;
using System.Collections.Generic;
using BIT.Objects;
using BIT.Common;
using BIT.DataHelper;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace BIT.DataHelper
{ 
	public class PH_DH : DataAccessBase
	{	
		public void InsertItem(PH obj)
		{
			defaultDB.ExecuteNonQuery("sp_PH_Insert"
				, obj.CodeId, obj.Amount, obj.CurrentAmount, obj.CreateDate, obj.Status);
		}

		public void UpdateItem(PH obj)
		{
			defaultDB.ExecuteNonQuery("sp_PH_Update"
				, obj.ID, obj.CodeId, obj.Amount, obj.CurrentAmount, obj.CreateDate, obj.Status);
		}

		public void DeleteItem(int ID)
		{
			defaultDB.ExecuteNonQuery("sp_PH_Delete"
				, ID);
		}

		public PH SelectItem(int ID)
		{
			return defaultDB.ExecuteSprocAccessor<PH>("sp_PH_SelectItem"
				, ID).FirstOrDefault();
		}

		public IEnumerable<PH> SelectAllItems()
		{
			return defaultDB.ExecuteSprocAccessor<PH>("sp_PH_SelectAllItems");
		}

		public bool IsExistsItem(int ID)
		{
			IDataReader dr  = defaultDB.ExecuteReader("sp_PH_SelectItem"
				, ID);
			
			bool bol = dr.Read();
			dr.Close();
			
			return bol;
		}

        public int GetNumberPH(string CodeId)
        {
            var iCount = defaultDB.ExecuteScalar("sp_PH_GetNumberPH", CodeId);

            return Convert.ToInt32(iCount);
        }

        public IEnumerable<PH> SelectItemsByCodeId(string CodeId)
        {
            return defaultDB.ExecuteSprocAccessor<PH>("sp_PH_SelectItemsByCodeId", CodeId);
        }

        public IEnumerable<PH_Info> SelectItemsByNumber(int numberPH)
        {
            return defaultDB.ExecuteSprocAccessor<PH_Info>("sp_PH_SelectItemsByNumber",numberPH);
        }

        public IEnumerable<PH_Info> SelectItemsByUserNameList(string strUserName)
        {
            return defaultDB.ExecuteSprocAccessor<PH_Info>("sp_PH_SelectItemsByUserNameList", strUserName);
        }

        public void UpdateStatusWithTrans(DbTransaction trans, int ID, int Status)
        {
            defaultDB.ExecuteNonQuery(trans, "sp_PH_UpdateStatus"
                , ID, Status);
        }

        public bool Check_Visible_DetailButton(int PH_ID)
        {
            var iCount = defaultDB.ExecuteScalar("sp_PH_Check_Visible_DetailButton", PH_ID);

            if (Convert.ToInt32(iCount) > 0)
                return true;
            else
                return false;
        }        
	}
}
