
// =============================================
// This Class is generated by BuildProject 
// Author:	Bop
// Create date:	07/09/2016 20:08
// Description:	
// Revise History:	
// =============================================

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using BIT.DataHelper;
using BIT.Objects;
using BIT.Common;

namespace BIT.Controller
{
    public class COMMAND_BC
    {
        COMMAND_DH ctl = new COMMAND_DH();

        public void InsertItem(COMMAND obj)
        {
            ctl.InsertItem(obj);
        }

        public void UpdateItem(COMMAND obj)
        {
            ctl.UpdateItem(obj);
        }

        public void DeleteItem(int ID)
        {
            ctl.DeleteItem(ID);
        }

        public COMMAND SelectItem(int ID)
        {
            return ctl.SelectItem(ID);
        }

        public List<COMMAND> SelectAllItems()
        {
            return ctl.SelectAllItems().ToList();
        }

        public bool IsExistsItem(int ID)
        {
            return ctl.IsExistsItem(ID);
        }

        public void InsertWithTransaction(COMMAND _command, List<COMMAND_DETAIL> _lstCommandDetails, List<GH_Info> _lstGH_Admin)
        {
            ctl.InsertWithTransaction(_command, _lstCommandDetails, _lstGH_Admin);
        }
    }
       
}
