
// =============================================
// This Class is generated by BuildProject 
// Author:	Bop
// Create date:	07/09/2016 20:08
// Description:	
// Revise History:	
// =============================================

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using BIT.DataHelper;
using BIT.Objects;
using BIT.Common;

namespace BIT.Controller
{ 
	public class GH_BC
	{
		GH_DH ctl = new GH_DH();
		
		public void InsertItem(GH obj)		
		{
			ctl.InsertItem(obj);
		}

		public void UpdateItem(GH obj)
		{
			ctl.UpdateItem(obj);
		}

        public void UpdateStatus(int ID, int Status)
        {
            ctl.UpdateStatus(ID, Status);
        }
		public void DeleteItem(int ID)
		{
			ctl.DeleteItem(ID);
		}

		public GH SelectItem(int ID)
		{
			return ctl.SelectItem(ID);
		}

		public List<GH> SelectAllItems()
		{
			return ctl.SelectAllItems().ToList();
		}
		
		public bool IsExistsItem(int ID)
		{
			return ctl.IsExistsItem(ID);
		}


        public List<GH_Info> SelectItemsByNumber(int numberGH)
        {
            return ctl.SelectItemsByNumber(numberGH).ToList();
        }

        public List<GH_Info> SelectItemsByName(string username)
        {
            return ctl.SelectItemsByName(username).ToList();
        }

        public List<GH_Info> SelectItemsByNameList(string username)
        {
            return ctl.SelectItemsByNameList(username).ToList();
        }

        public List<GH_Info> SelectWaitingGH()
        {
            return ctl.SelectWaitingGH().ToList();
        }

        public List<GH_Info> SelectAdminMemberGH()
        {
            return ctl.SelectAdminMemberGH().ToList();
        }

        public bool Check_Visible_DetailButton(int GH_ID)
        {
            return ctl.Check_Visible_DetailButton(GH_ID);
        }

        public List<GH> SelectItemsByCodeId(string CodeId)
        {
            return ctl.SelectItemsByCodeId(CodeId).ToList();
        }
	}
}
