
// =============================================
// This Class is generated by BuildProject 
// Author:	Bop
// Create date:	07/09/2016 20:08
// Description:	
// Revise History:	
// =============================================

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using BIT.DataHelper;
using BIT.Objects;
using BIT.Common;

namespace BIT.Controller
{
    public class PIN_TRANSACTION_BC
	{
        PIN_TRANSACTION_DH ctl = new PIN_TRANSACTION_DH();

        public void InsertItem(PIN_TRANSACTION obj)		
		{
			ctl.InsertItem(obj);
		}

        public void UpdateItem(int pin_transaction_id)
		{
            ctl.UpdateItem(pin_transaction_id);
		}

        public void AdminConfirm(int pin_transaction_id)
        {
            ctl.AdminConfirm(pin_transaction_id);
        }

		public void DeleteItem(int ID)
		{
			ctl.DeleteItem(ID);
		}

        public PIN_TRANSACTION SelectItem(int ID)
		{
			return ctl.SelectItem(ID);
		}

        public List<PIN_TRANSACTION> SelectAllItems(string codeID)
		{
			return ctl.SelectAllItems(codeID).ToList();
		}
		
		public bool IsExistsItem(int ID)
		{
			return ctl.IsExistsItem(ID);
		}
	}
}
