
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	07/09/2016 20:08
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{ 
	public class COMMAND
	{
		
	public int ID { get; set; }
	
	public string CommandCode { get; set; }
	
	public string UserCreate { get; set; }
	
	public DateTime? DateCreate { get; set; }
		
	}
}


