
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	07/09/2016 20:08
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class GH
    {

        public int ID { get; set; }

        public string CodeId { get; set; }

        public decimal? Amount { get; set; }

        public decimal? CurrentAmount { get; set; }

        public DateTime? CreateDate { get; set; }

        public int? Status { get; set; }

    }

    [Serializable]
    public class GH_Info
    {

        public int ID { get; set; }

        public string CodeId { get; set; }

        public decimal? Amount { get; set; }

        public decimal? CurrentAmount { get; set; }

        public DateTime? CreateDate { get; set; }

        public int? Status { get; set; }
        public string Username { get; set; }

    }
}


