
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	07/09/2016 20:08
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class PIN_TRANSACTION
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public int Package_TransactionID { get; set; }
        public string CODE_ID { get; set; }
        public int MONTH { get; set; }
        public decimal AMOUNT { get; set; }
        public bool CONFIRM_SEND { get; set; }
        public int STATUS { get; set; }
        public DateTime CREATE_DATE { get; set; }
        public string TRANSACTION_PIN { get; set; }
        public DateTime CONFIRM_DATE { get; set; }
        public DateTime FROM_DATE { get; set; }
        public DateTime TO_DATE { get; set; }
    }


}


