
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	17/08/2016 11:31
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class WALLET
    {

        public int ID { get; set; }

        public String Code_Id { get; set; }

        public decimal? R_Wallet { get; set; }

        public decimal? C_Wallet { get; set; }

        public decimal? PIN_Wallet { get; set; }

    }
}


