
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	17/08/2016 11:31
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class WITHDRAW
    {

        public int ID { get; set; }

        public String CodeId { get; set; }

        public decimal? Amount { get; set; }

        public DateTime? Date_Create { get; set; }

        public string TransactionId { get; set; }

        public int? Status { get; set; }

        public string Wallet {get;set;}

        public string username { get; set; }
    }
}


